name: Build iso
on:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Set variables
        run: |
          VER=$(cat version.md | head -n1 | sed -e "s/# //")
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Build iso
        run: |
          cd $GITHUB_WORKSPACE
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S base-devel archiso git wget neofetch --noconfirm
          neofetch
          ls
          mkdir output
          mkarchiso -v -o output ./
      - name: Upload and release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: archiso-with-plasma
          path: output/*.iso
      - uses: softprops/action-gh-release@v1
        with:
          files: 'output/*.iso'
          tag_name: ${{ env.VERSION }}
          release_name: ArchISO with DEs ${{ env.VERSION }}
          body_path: "version.md"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
