name: Build iso

on:
  
  schedule:
    
    - cron: "0 6 * * 0"
  
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    container: 
      
      image: archlinux
      
      options: --privileged
    
    steps:
      
      - uses: actions/checkout@v2
      
      - name: Build iso
        run: |
          cd $GITHUB_WORKSPACE
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S base-devel archiso git wget neofetch --noconfirm
          neofetch
          ls
          mkdir output
          mkarchiso -v -o output ./
          
      - name: Upload and release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: archiso-with-plasma
          path: output/*.iso
      
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'Dev'
          rm: true
          files: output/*.iso
        if: github.event_name == 'push'
      
      - uses: softprops/action-gh-release@v1
        with:
          files: 'output/*.iso'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
