# This is a basic workflow to help you get started with Actions

name: Build arch

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 6 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install Archiso
        run: |
          cd $GITHUB_WORKSPACE
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S archiso git --noconfirm
      
      - name: build the image 
          mkarchiso -v .
          find out/
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: archiso-with-plasma
          path: out/*.iso
