name: Build iso
on:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Build iso
        run: |
          cd $GITHUB_WORKSPACE
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S base-devel archiso git wget neofetch --noconfirm
          neofetch
          ls
          mkdir kde/output
          mkarchiso -v -o kde/output ./
      - name: Upload and release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: archiso-with-plasma
          path: kde/output/*.iso
      - uses: softprops/action-gh-release@v1
        with:
          files: 'kde/output/*.iso'
          tag_name: 'Release'
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
