name: Build arch

on:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Install Archiso and build the image
        run: |
          cd $GITHUB_WORKSPACE
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S archiso git --noconfirm
          mkarchiso -v .
          find out/
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: archiso-with-plasma
          path: out/*.iso
