name: Build the isos

on:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:

jobs:
  build-plasma:
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S base-devel archiso git wget neofetch --noconfirm
          # lmao why not
          neofetch
          mkdir output
          mkarchiso -v -o output plasma
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: archiso-with-plasma
          path: output/*.iso
  build-gnome:
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S base-devel archiso git wget neofetch --noconfirm
          # lmao why not
          neofetch
          mkdir output
          mkarchiso -v -o output gnome
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: archiso-with-gnome
          path: output/*.iso