# This is a basic workflow to help you get started with Actions

name: Build the image

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 6 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S base-devel archiso git wget neofetch --noconfirm
          # lmao why not
          neofetch
          git clone https://github.com/chinh4thepro/arch-install-iso-with-plasma.git
          ls
          mkdir output
          mkarchiso -v -o output arch-install-iso-with-plasma
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          path: output/archlinux-*-x86_64.iso
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: True
          release_name: Test release
        env:
          GITHUB_TOKEN: ${{ github.token }}
