# This is a basic workflow to help you get started with Actions

name: Build the image

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S base-devel archiso git wget neofetch --noconfirm
          neofetch
          ls
          mkdir output
          mkarchiso -v -o output arch-install-iso-with-plasma
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: archiso-with-plasma
          path: output/*.iso
